In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### **Loading the dataset**

In [2]:
data = pd.read_csv('train.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### **Checking null values using isnull().sum()**

In [3]:
print(data.isnull().sum())

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [4]:
x = data.isnull().sum()

i = 0
for a in data.isnull().sum():
    print(x.index[i],' : ',a)
    i+=1

Id  :  0
MSSubClass  :  0
MSZoning  :  0
LotFrontage  :  259
LotArea  :  0
Street  :  0
Alley  :  1369
LotShape  :  0
LandContour  :  0
Utilities  :  0
LotConfig  :  0
LandSlope  :  0
Neighborhood  :  0
Condition1  :  0
Condition2  :  0
BldgType  :  0
HouseStyle  :  0
OverallQual  :  0
OverallCond  :  0
YearBuilt  :  0
YearRemodAdd  :  0
RoofStyle  :  0
RoofMatl  :  0
Exterior1st  :  0
Exterior2nd  :  0
MasVnrType  :  8
MasVnrArea  :  8
ExterQual  :  0
ExterCond  :  0
Foundation  :  0
BsmtQual  :  37
BsmtCond  :  37
BsmtExposure  :  38
BsmtFinType1  :  37
BsmtFinSF1  :  0
BsmtFinType2  :  38
BsmtFinSF2  :  0
BsmtUnfSF  :  0
TotalBsmtSF  :  0
Heating  :  0
HeatingQC  :  0
CentralAir  :  0
Electrical  :  1
1stFlrSF  :  0
2ndFlrSF  :  0
LowQualFinSF  :  0
GrLivArea  :  0
BsmtFullBath  :  0
BsmtHalfBath  :  0
FullBath  :  0
HalfBath  :  0
BedroomAbvGr  :  0
KitchenAbvGr  :  0
KitchenQual  :  0
TotRmsAbvGrd  :  0
Functional  :  0
Fireplaces  :  0
FireplaceQu  :  690
GarageType  :  81
GarageYrBlt  :  81
GarageFinish  :  81
GarageCars  :  0
GarageArea  :  0
GarageQual  :  81
GarageCond  :  81
PavedDrive  :  0
WoodDeckSF  :  0
OpenPorchSF  :  0
EnclosedPorch  :  0
3SsnPorch  :  0
ScreenPorch  :  0
PoolArea  :  0
PoolQC  :  1453
Fence  :  1179
MiscFeature  :  1406
MiscVal  :  0
MoSold  :  0
YrSold  :  0
SaleType  :  0
SaleCondition  :  0
SalePrice  :  0

In [5]:
type(data.isnull().sum())

pandas.core.series.Series

In [6]:
x = data.isnull().sum()

In [7]:
print(x.index)

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

### **Percentage of null values using isnull().mean()**

In [8]:
 y = data.isnull().mean()

In [9]:
i = 0
for a in data.isnull().mean():
    print(y.index[i],' : ',a)
    i+=1

Id  :  0.0
MSSubClass  :  0.0
MSZoning  :  0.0
LotFrontage  :  0.1773972602739726
LotArea  :  0.0
Street  :  0.0
Alley  :  0.9376712328767123
LotShape  :  0.0
LandContour  :  0.0
Utilities  :  0.0
LotConfig  :  0.0
LandSlope  :  0.0
Neighborhood  :  0.0
Condition1  :  0.0
Condition2  :  0.0
BldgType  :  0.0
HouseStyle  :  0.0
OverallQual  :  0.0
OverallCond  :  0.0
YearBuilt  :  0.0
YearRemodAdd  :  0.0
RoofStyle  :  0.0
RoofMatl  :  0.0
Exterior1st  :  0.0
Exterior2nd  :  0.0
MasVnrType  :  0.005479452054794521
MasVnrArea  :  0.005479452054794521
ExterQual  :  0.0
ExterCond  :  0.0
Foundation  :  0.0
BsmtQual  :  0.025342465753424658
BsmtCond  :  0.025342465753424658
BsmtExposure  :  0.026027397260273973
BsmtFinType1  :  0.025342465753424658
BsmtFinSF1  :  0.0
BsmtFinType2  :  0.026027397260273973
BsmtFinSF2  :  0.0
BsmtUnfSF  :  0.0
TotalBsmtSF  :  0.0
Heating  :  0.0
HeatingQC  :  0.0
CentralAir  :  0.0
Electrical  :  0.0006849315068493151
1stFlrSF  :  0.0
2ndFlrSF  :  0.0
LowQualFinSF  :  0.0
GrLivArea  :  0.0
BsmtFullBath  :  0.0
BsmtHalfBath  :  0.0
FullBath  :  0.0
HalfBath  :  0.0
BedroomAbvGr  :  0.0
KitchenAbvGr  :  0.0
KitchenQual  :  0.0
TotRmsAbvGrd  :  0.0
Functional  :  0.0
Fireplaces  :  0.0
FireplaceQu  :  0.4726027397260274
GarageType  :  0.05547945205479452
GarageYrBlt  :  0.05547945205479452
GarageFinish  :  0.05547945205479452
GarageCars  :  0.0
GarageArea  :  0.0
GarageQual  :  0.05547945205479452
GarageCond  :  0.05547945205479452
PavedDrive  :  0.0
WoodDeckSF  :  0.0
OpenPorchSF  :  0.0
EnclosedPorch  :  0.0
3SsnPorch  :  0.0
ScreenPorch  :  0.0
PoolArea  :  0.0
PoolQC  :  0.9952054794520548
Fence  :  0.8075342465753425
MiscFeature  :  0.963013698630137
MiscVal  :  0.0
MoSold  :  0.0
YrSold  :  0.0
SaleType  :  0.0
SaleCondition  :  0.0
SalePrice  :  0.0

## **Missing data not at random (MNAR)**

**(percentage of null values is greater than 90%)**

In [10]:
#MiscFeature(96),PoolQC(99),Alley(93)
i = 0
ar = []
for a in y:
    if a >= 0.9  :
        print(y.index[i],' : ',a)
        ar.append(y.index[i])
    i+=1

Alley  :  0.9376712328767123
PoolQC  :  0.9952054794520548
MiscFeature  :  0.963013698630137

In [11]:
ar

['Alley', 'PoolQC', 'MiscFeature']

In [12]:
df = data.drop(ar,axis = 1)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,NaN,0,12,2008,WD,Normal,250000

In [13]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [14]:
i = 0
for a in y:
    if a :
        print(y.index[i],'  : ',a)
    i += 1

LotFrontage   :  0.1773972602739726
Alley   :  0.9376712328767123
MasVnrType   :  0.005479452054794521
MasVnrArea   :  0.005479452054794521
BsmtQual   :  0.025342465753424658
BsmtCond   :  0.025342465753424658
BsmtExposure   :  0.026027397260273973
BsmtFinType1   :  0.025342465753424658
BsmtFinType2   :  0.026027397260273973
Electrical   :  0.0006849315068493151
FireplaceQu   :  0.4726027397260274
GarageType   :  0.05547945205479452
GarageYrBlt   :  0.05547945205479452
GarageFinish   :  0.05547945205479452
GarageQual   :  0.05547945205479452
GarageCond   :  0.05547945205479452
PoolQC   :  0.9952054794520548
Fence   :  0.8075342465753425
MiscFeature   :  0.963013698630137

In [15]:
data['Fence_isnull'] = np.where(data['Fence'].isnull(),1,0)
data['Fence_isnull'].head(20)

0     1
1     1
2     1
3     1
4     1
5     0
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    0
15    0
16    1
17    1
18    1
19    0
Name: Fence_isnull, dtype: int32

In [16]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Fence_isnull
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,1
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,1
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,1

**value_counts() is used to find the frequency of each unique value**

In [17]:
data['Street'].value_counts()

Pave    1454
Grvl       6
Name: Street, dtype: int64

**groupby() is used to group the data based on a particular category and check how many null values are there in each category**

In [18]:
z = data.groupby(['Street'])['Fence_isnull'].mean()
# type(z)
z

Street
Grvl    1.00000
Pave    0.80674
Name: Fence_isnull, dtype: float64

In [19]:
for key, item in data.groupby(['Street']):
#     print(z.get_group(key))
    print(key,item['Fence_isnull'])

Grvl 52      1
335     1
582     1
812     1
1061    1
1184    1
Name: Fence_isnull, dtype: int32
Pave 0       1
1       1
2       1
3       1
4       1
       ..
1455    1
1456    0
1457    0
1458    1
1459    1
Name: Fence_isnull, Length: 1454, dtype: int32

In [20]:
#ALTERNATIVE

data['Alley'].isnull().groupby(data['Street']).mean()

Street
Grvl    1.000000
Pave    0.937414
Name: Alley, dtype: float64

In [21]:
df['Street'].value_counts()

Pave    1454
Grvl       6
Name: Street, dtype: int64

**nunique() to check number of unique values in each column**

In [22]:
print("No of unique values in 'Street' :")
df["Street"].nunique()

No of unique values in 'Street' :

2

## ***Seperating numerical and categorical features**

In [23]:
# HOW TO SEPARATE BEWTEEN NUMERICAL & CATEGORICAL ?

numerical = []
categorical = []
for col in df.columns :
    if df[col].nunique() > 7:
        numerical.append(col)
    else :
        categorical.append(col)

categorical

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'BldgType',
 'RoofStyle',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'KitchenAbvGr',
 'KitchenQual',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageCars',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'Fence',
 'YrSold',
 'SaleCondition']

In [24]:
y

Id               0.000000
MSSubClass       0.000000
MSZoning         0.000000
LotFrontage      0.177397
LotArea          0.000000
                   ...
MoSold           0.000000
YrSold           0.000000
SaleType         0.000000
SaleCondition    0.000000
SalePrice        0.000000
Length: 81, dtype: float64

In [25]:
i = 0
for a in y :
    if a < 0.02 and a != 0:
        print(y.index[i],"  : ",a)
    i += 1

MasVnrType   :  0.005479452054794521
MasVnrArea   :  0.005479452054794521
Electrical   :  0.0006849315068493151